---
apiVersion: v1
kind: Pod
metadata:
  name: log
  labels:
    pod: log
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-007
  initContainers:
  - name: chmod
    image: busybox
    args:
    - chown
    - 1000:1000
    - /data
    volumeMounts:
    - name: data-dir
      mountPath: /data
    resources: &resources
      limits:
        cpu: 4000m
        memory: 4000Mi
  containers:
  - name: kibana
    image: elastic/kibana:7.12.1
    resources: *resources
    env:
    - name: ELASTICSEARCH_HOSTS
      value: http://localhost:9200
  - name: elasticsearch
    image: elastic/elasticsearch:7.12.1
    resources: *resources
    env:
    - name: discovery.type
      value: single-node
    - name: bootstrap.memory_lock
      value: "true"
    - name: ES_JAVA_OPTS
      value: "-Xms256m -Xmx256m"
    volumeMounts:
    - name: data-dir
      mountPath: /usr/share/elasticsearch/data
  - name: filebeat
    image: lwzm/log
    resources: *resources
    env:
    - name: NAME
      value: x
    - name: ES
      value: localhost
  volumes:
  - name: data-dir
    hostPath:
      path: /data/lwzm/log
      type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: log
spec:
  clusterIP: None
  selector:
    pod: log
  ports:
  - name: kibana
    port: 5601
  - name: elasticsearch
    port: 9200
